---
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:default;MODE=MySQL;DB_CLOSE_DELAY=-1
    username: sa
    password:
  sql:
    init:
      mode: embedded
      schema-locations:
        - classpath:h2/init.sql
      data-locations:
        - classpath:h2/data.sql
  h2:
    console:
      enabled: true

logging:
  level:
    root: info
    web: debug
    org.seasar.doma.jdbc.UtilLoggingJdbcLogger: debug
    org.springframework.jdbc.datasource.init: debug

doma:
  dialect: h2