---
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3314/job_db
    username: user
    password: password

logging:
  level:
    root: info
    web: debug
    org.seasar.doma.jdbc.UtilLoggingJdbcLogger: debug
    org.springframework.jdbc.datasource.init: debug

