---
spring:
  application:
    name: job-sample-api
  messages:
    encoding: UTF-8
  jackson:
    time-zone: "Asia/Tokyo"
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3314/job_db
    username: user
    password: password

logging:
  level:
    root: info

doma:
  dialect: mysql
  naming: snake_lower_case

# openapi-spring-doc(swagger) の設定
# https://swagger.io/docs/open-source-tools/swagger-ui/usage/configuration/
springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    display-request-duration: false
    tags-sorter: method
    defaultModelRendering: example
    doc-expansion: list
    config-url: /v3/api-docs/swagger-config
    url: /v3/api-docs